sudo: required

dist: trusty

language: node_js

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install -g codecov

script:
  - "npm run lint"
  - "npm test -- --coverage"
  - "cd tests/unit/coverage && codecov"

# set assetsPublicPath to gitvub path
# sed -i "0,/assetsPublicPath: '\/'/s//assetsPublicPath: '\/gitvub'/" config/index.js
before_deploy:
  - "cd ../../.."
  - "sed -i \"0,/assetsPublicPath: '\/'/s//assetsPublicPath: '\/gitvub'/\" config/index.js"
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
